In [1]:
import pandas as pd
import random

# Use demographic csv
data = pd.read_csv('../GAN-neural-imaging/csvfiles/1139_Demographics_20150429.csv')

# Display the first few rows of the DataFrame
data.head()

,Unnamed: 0,Unnamed: 1,Current Age,Gender,Ethnicity,Race,Marital Status,Your highest level of Education,Highest Level of Education for Primary Caretaker until 18 years old,Highest Level of Education for Secondary Caretaker until subject was 18 years old,...,"If yes, the Loss of Concientious Time",First degree relative with psychosis,"If yes, what is the likely diagnosis",Age at first psychiatric illness,"Age at first psychotic symptoms?(e.g., delusions, hallucinations, thought disorder)",Age at first psychiatric hospitalization,Number of hospitalizations for psychiatric illness?,Total duration of psychiatric hospitalizations,"Time since last psychiatric hospitalization? if patient is identified during an admission, record time since prior hospitalization",How long had the patient been treated in an outpatient setting?
0,Anonymized ID,Subject Type,CODEM_1,CODEM_2,CODEM_3,CODEM_3A,CODEM_4,CODEM_5,CODEM_6,CODEM_7,...,CODEM_13,CODEM_14,CODEM_15,CODEM_16,CODEM_17,CODEM_18,CODEM_19,CODEM_20,CODEM_21,CODEM_22
1,A00009280,Schizophrenia,23,1,0,2,3,4,8,8,...,NaN,1,NaN,21,21,21,1,2.5,18,18
2,A00028806,Schizophrenia,25,1,0,3,3,2,3,2,...,NaN,1,NaN,21,11,20,2,2,24,72
3,A00007409,Control,47,1,0,5,2,5,8,9999,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A00023132,Schizophrenia,49,1,0,5,3,3,6,6,...,NaN,1,NaN,28,28,NaN,NaN,NaN,NaN,144

In [2]:
data.dtypes

Unnamed: 0                                                                                                                            object
Unnamed: 1                                                                                                                            object
Current Age                                                                                                                           object
Gender                                                                                                                                object
Ethnicity                                                                                                                             object
Race                                                                                                                                  object
Marital Status                                                                                                                        object
Your highest level of Education                                                                                                       object
Highest Level of Education for Primary Caretaker until 18 years old                                                                   object
Highest Level of Education for Secondary Caretaker until subject was 18 years old                                                     object
Your highest level of Occupation                                                                                                      object
Highest  Level of Occupation for Primary Caretaker                                                                                    object
Highest Level of Occupation for Secondary Caretaker                                                                                   object
Handedness                                                                                                                            object
Head Injury History                                                                                                                   object
If yes, the date                                                                                                                      object
If yes, the Loss of Concientious Time                                                                                                 object
First degree relative with psychosis                                                                                                  object
If yes, what is the likely diagnosis                                                                                                  object
Age at first psychiatric illness                                                                                                      object
Age at first psychotic symptoms?(e.g., delusions, hallucinations, thought disorder)                                                   object
Age at first psychiatric hospitalization                                                                                              object
Number of hospitalizations for psychiatric illness?                                                                                   object
Total duration of psychiatric hospitalizations                                                                                        object
Time since last psychiatric hospitalization? if patient is identified during an admission, record time since prior hospitalization    object
How long had the patient been treated in an outpatient setting?                                                                       object
dtype: object

In [3]:
data.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Current Age', 'Gender', 'Ethnicity',
       'Race', 'Marital Status', 'Your highest level of Education',
       'Highest Level of Education for Primary Caretaker until 18 years old',
       'Highest Level of Education for Secondary Caretaker until subject was 18 years old',
       'Your highest level of Occupation',
       'Highest  Level of Occupation for Primary Caretaker',
       'Highest Level of Occupation for Secondary Caretaker', 'Handedness',
       'Head Injury History', 'If yes, the date',
       'If yes, the Loss of Concientious Time',
       'First degree relative with psychosis',
       'If yes, what is the likely diagnosis',
       'Age at first psychiatric illness',
       'Age at first psychotic symptoms?(e.g., delusions, hallucinations, thought disorder)',
       'Age at first psychiatric hospitalization',
       'Number of hospitalizations for psychiatric illness?',
       'Total duration of psychiatric hospitalizations',
       'Time since last psychiatric hospitalization? if patient is identified during an admission, record time since prior hospitalization',
       'How long had the patient been treated in an outpatient setting?'],
      dtype='object')

In [4]:
# How many patients of each type?
unique_values_count = data['Unnamed: 1'].value_counts()
unique_values_count

Control            99
Schizophrenia      86
Schizoaffective    13
Bipolar            10
Subject Type        1
Name: Unnamed: 1, dtype: int64

In [5]:
schizophrenia_count = (data['Unnamed: 1'] == 'Schizophrenia').sum()
schizophrenia_count

86

In [6]:
# Filter rows where 'Unnamed: 1' column contains 'Schizophrenia' and extract the 'Unnamed: 0' column
schizophrenia_ids = data.loc[data['Unnamed: 1'] == 'Schizophrenia', 'Unnamed: 0']

# Convert the result to a list
schizophrenia_id_list = schizophrenia_ids.tolist()

# Print the list of IDs
print("IDs of individuals with schizophrenia:")
for id in schizophrenia_id_list:
    print(f" '{id}' ,")

print("how many schizophrenic?" ,len(schizophrenia_id_list))

IDs of individuals with schizophrenia:
 'A00009280' ,
 'A00028806' ,
 'A00023132' ,
 'A00014804' ,
 'A00016859' ,
 'A00021598' ,
 'A00001181' ,
 'A00023158' ,
 'A00024568' ,
 'A00028405' ,
 'A00001251' ,
 'A00000456' ,
 'A00015648' ,
 'A00002405' ,
 'A00027391' ,
 'A00016720' ,
 'A00018434' ,
 'A00016197' ,
 'A00027119' ,
 'A00006754' ,
 'A00009656' ,
 'A00038441' ,
 'A00012767' ,
 'A00034273' ,
 'A00028404' ,
 'A00035485' ,
 'A00024684' ,
 'A00018979' ,
 'A00027537' ,
 'A00004507' ,
 'A00001452' ,
 'A00023246' ,
 'A00027410' ,
 'A00014719' ,
 'A00024510' ,
 'A00000368' ,
 'A00019293' ,
 'A00014830' ,
 'A00015201' ,
 'A00018403' ,
 'A00037854' ,
 'A00024198' ,
 'A00001243' ,
 'A00014590' ,
 'A00002337' ,
 'A00024953' ,
 'A00037224' ,
 'A00027616' ,
 'A00001856' ,
 'A00037619' ,
 'A00024228' ,
 'A00038624' ,
 'A00037034' ,
 'A00037649' ,
 'A00022500' ,
 'A00013216' ,
 'A00020787' ,
 'A00028410' ,
 'A00002480' ,
 'A00028303' ,
 'A00020602' ,
 'A00024959' ,
 'A00018598' ,
 'A00014636' ,
 'A00019349' ,
 'A00017147' ,
 'A00023590' ,
 'A00023750' ,
 'A00031597' ,
 'A00015518' ,
 'A00018317' ,
 'A00016723' ,
 'A00021591' ,
 'A00023243' ,
 'A00017943' ,
 'A00023366' ,
 'A00014607' ,
 'A00020414' ,
 'A00035003' ,
 'A00028805' ,
 'A00029486' ,
 'A00000541' ,
 'A00028408' ,
 'A00000909' ,
 'A00031186' ,
 'A00000838' ,
how many schizophrenic? 86

In [7]:
print("IDs of individuals with schizophrenia: ", end="")
print(", ".join(f"'{id}'" for id in schizophrenia_id_list))

IDs of individuals with schizophrenia: 'A00009280', 'A00028806', 'A00023132', 'A00014804', 'A00016859', 'A00021598', 'A00001181', 'A00023158', 'A00024568', 'A00028405', 'A00001251', 'A00000456', 'A00015648', 'A00002405', 'A00027391', 'A00016720', 'A00018434', 'A00016197', 'A00027119', 'A00006754', 'A00009656', 'A00038441', 'A00012767', 'A00034273', 'A00028404', 'A00035485', 'A00024684', 'A00018979', 'A00027537', 'A00004507', 'A00001452', 'A00023246', 'A00027410', 'A00014719', 'A00024510', 'A00000368', 'A00019293', 'A00014830', 'A00015201', 'A00018403', 'A00037854', 'A00024198', 'A00001243', 'A00014590', 'A00002337', 'A00024953', 'A00037224', 'A00027616', 'A00001856', 'A00037619', 'A00024228', 'A00038624', 'A00037034', 'A00037649', 'A00022500', 'A00013216', 'A00020787', 'A00028410', 'A00002480', 'A00028303', 'A00020602', 'A00024959', 'A00018598', 'A00014636', 'A00019349', 'A00017147', 'A00023590', 'A00023750', 'A00031597', 'A00015518', 'A00018317', 'A00016723', 'A00021591', 'A00023243', 'A00017943', 'A00023366', 'A00014607', 'A00020414', 'A00035003', 'A00028805', 'A00029486', 'A00000541', 'A00028408', 'A00000909', 'A00031186', 'A00000838'

In [8]:
# Take a random subset of n IDs
random_subset = random.sample(schizophrenia_id_list, 10)

# Print the random subset of IDs
print("Random subset of 10 IDs of individuals with schizophrenia:")
for id in random_subset:
    print(id)

Random subset of 10 IDs of individuals with schizophrenia:
A00015201
A00024959
A00037854
A00023158
A00027391
A00017943
A00020602
A00035003
A00023132
A00002337

In [9]:
non_schizophrenia_count = (data['Unnamed: 1'] != 'Schizophrenia').sum()
non_schizophrenia_count

123

In [10]:
# non-schizphrenic include some other types as well

non_schizophrenia_ids = data.loc[data['Unnamed: 1'] != 'Schizophrenia', 'Unnamed: 0']

non_schizophrenia_id_list = non_schizophrenia_ids.tolist()

# Print the list of IDs
print("IDs of individuals with non_schizophrenia:")
for id2 in non_schizophrenia_id_list:
     print(f" '{id2}' ,")

IDs of individuals with non_schizophrenia:
 'Anonymized ID' ,
 'A00007409' ,
 'A00013140' ,
 'A00021145' ,
 'A00036049' ,
 'A00022810' ,
 'A00002198' ,
 'A00020895' ,
 'A00004667' ,
 'A00015826' ,
 'A00023120' ,
 'A00022837' ,
 'A00010684' ,
 'A00009946' ,
 'A00037318' ,
 'A00033214' ,
 'A00022490' ,
 'A00023848' ,
 'A00035859' ,
 'A00029452' ,
 'A00037564' ,
 'A00036555' ,
 'A00023095' ,
 'A00022729' ,
 'A00024955' ,
 'A00024160' ,
 'A00011725' ,
 'A00028402' ,
 'A00027487' ,
 'A00024446' ,
 'A00014898' ,
 'A00015759' ,
 'A00033994' ,
 'A00028409' ,
 'A00031271' ,
 'A00017294' ,
 'A00014522' ,
 'A00012995' ,
 'A00031764' ,
 'A00025969' ,
 'A00033147' ,
 'A00018553' ,
 'A00023143' ,
 'A00036916' ,
 'A00028052' ,
 'A00023337' ,
 'A00023730' ,
 'A00020805' ,
 'A00020984' ,
 'A00000300' ,
 'A00010150' ,
 'A00024932' ,
 'A00014175' ,
 'A00035537' ,
 'A00022509' ,
 'A00033812' ,
 'A00028406' ,
 'A00034381' ,
 'A00004087' ,
 'A00035751' ,
 'A00023800' ,
 'A00027787' ,
 'A00035836' ,
 'A00022687' ,
 'A00023866' ,
 'A00021085' ,
 'A00022619' ,
 'A00036897' ,
 'A00019888' ,
 'A00021058' ,
 'A00022835' ,
 'A00021432' ,
 'A00033749' ,
 'A00037495' ,
 'A00026945' ,
 'A00018716' ,
 'A00028189' ,
 'A00019750' ,
 'A00026907' ,
 'A00023330' ,
 'A00033686' ,
 'A00016199' ,
 'A00027755' ,
 'A00037238' ,
 'A00023131' ,
 'A00014120' ,
 'A00021072' ,
 'A00027969' ,
 'A00033715' ,
 'A00037665' ,
 'A00011107' ,
 'A00022400' ,
 'A00003150' ,
 'A00024372' ,
 'A00021081' ,
 'A00038172' ,
 'A00033648' ,
 'A00022592' ,
 'A00022653' ,
 'A00013816' ,
 'A00014839' ,
 'A00031478' ,
 'A00014225' ,
 'A00013363' ,
 'A00034214' ,
 'A00037007' ,
 'A00020968' ,
 'A00024301' ,
 'A00024820' ,
 'A00035469' ,
 'A00029226' ,
 'A00022915' ,
 'A00035183' ,
 'A00022773' ,
 'A00024663' ,
 'A00036844' ,
 'A00009207' ,
 'A00024535' ,
 'A00022727' ,
 'A00011265' ,
 'A00020416' ,
 'A00024546' ,
 'A00028403' ,

In [13]:
print("IDs of individuals with non_schizophrenia: ", end="")
print(", ".join(f"'{id2}'" for id2 in non_schizophrenia_id_list))

IDs of individuals with non_schizophrenia: 'Anonymized ID', 'A00007409', 'A00013140', 'A00021145', 'A00036049', 'A00022810', 'A00002198', 'A00020895', 'A00004667', 'A00015826', 'A00023120', 'A00022837', 'A00010684', 'A00009946', 'A00037318', 'A00033214', 'A00022490', 'A00023848', 'A00035859', 'A00029452', 'A00037564', 'A00036555', 'A00023095', 'A00022729', 'A00024955', 'A00024160', 'A00011725', 'A00028402', 'A00027487', 'A00024446', 'A00014898', 'A00015759', 'A00033994', 'A00028409', 'A00031271', 'A00017294', 'A00014522', 'A00012995', 'A00031764', 'A00025969', 'A00033147', 'A00018553', 'A00023143', 'A00036916', 'A00028052', 'A00023337', 'A00023730', 'A00020805', 'A00020984', 'A00000300', 'A00010150', 'A00024932', 'A00014175', 'A00035537', 'A00022509', 'A00033812', 'A00028406', 'A00034381', 'A00004087', 'A00035751', 'A00023800', 'A00027787', 'A00035836', 'A00022687', 'A00023866', 'A00021085', 'A00022619', 'A00036897', 'A00019888', 'A00021058', 'A00022835', 'A00021432', 'A00033749', 'A00037495', 'A00026945', 'A00018716', 'A00028189', 'A00019750', 'A00026907', 'A00023330', 'A00033686', 'A00016199', 'A00027755', 'A00037238', 'A00023131', 'A00014120', 'A00021072', 'A00027969', 'A00033715', 'A00037665', 'A00011107', 'A00022400', 'A00003150', 'A00024372', 'A00021081', 'A00038172', 'A00033648', 'A00022592', 'A00022653', 'A00013816', 'A00014839', 'A00031478', 'A00014225', 'A00013363', 'A00034214', 'A00037007', 'A00020968', 'A00024301', 'A00024820', 'A00035469', 'A00029226', 'A00022915', 'A00035183', 'A00022773', 'A00024663', 'A00036844', 'A00009207', 'A00024535', 'A00022727', 'A00011265', 'A00020416', 'A00024546', 'A00028403'

In [14]:
control_ids = data.loc[data['Unnamed: 1'] == 'Control', 'Unnamed: 0']

control_id_list = control_ids.tolist()

# Print the list of IDs
print("IDs of individuals with control:")
for id3 in control_id_list:
    print(id3)

print("how many controls?" ,len(control_id_list))

IDs of individuals with control:
A00007409
A00013140
A00021145
A00036049
A00022810
A00002198
A00020895
A00004667
A00015826
A00023120
A00022837
A00010684
A00009946
A00037318
A00033214
A00022490
A00023848
A00029452
A00037564
A00036555
A00023095
A00022729
A00024955
A00024160
A00011725
A00027487
A00024446
A00014898
A00015759
A00028409
A00017294
A00014522
A00012995
A00031764
A00025969
A00033147
A00018553
A00023143
A00036916
A00028052
A00023337
A00023730
A00020805
A00020984
A00000300
A00010150
A00024932
A00035537
A00022509
A00028406
A00004087
A00035751
A00023800
A00027787
A00022687
A00023866
A00021085
A00022619
A00036897
A00019888
A00021058
A00022835
A00037495
A00026945
A00018716
A00026907
A00023330
A00016199
A00037238
A00023131
A00014120
A00021072
A00037665
A00022400
A00003150
A00024372
A00021081
A00022592
A00022653
A00013816
A00014839
A00031478
A00014225
A00013363
A00037007
A00020968
A00024301
A00024820
A00035469
A00029226
A00022915
A00022773
A00024663
A00036844
A00009207
A00024535
A00022727
A00011265
A00024546
how many controls? 99

In [15]:
print("IDs of individuals with control: ", end="")
print(", ".join(f"'{id3}'" for id3 in control_id_list))

IDs of individuals with control: 'A00007409', 'A00013140', 'A00021145', 'A00036049', 'A00022810', 'A00002198', 'A00020895', 'A00004667', 'A00015826', 'A00023120', 'A00022837', 'A00010684', 'A00009946', 'A00037318', 'A00033214', 'A00022490', 'A00023848', 'A00029452', 'A00037564', 'A00036555', 'A00023095', 'A00022729', 'A00024955', 'A00024160', 'A00011725', 'A00027487', 'A00024446', 'A00014898', 'A00015759', 'A00028409', 'A00017294', 'A00014522', 'A00012995', 'A00031764', 'A00025969', 'A00033147', 'A00018553', 'A00023143', 'A00036916', 'A00028052', 'A00023337', 'A00023730', 'A00020805', 'A00020984', 'A00000300', 'A00010150', 'A00024932', 'A00035537', 'A00022509', 'A00028406', 'A00004087', 'A00035751', 'A00023800', 'A00027787', 'A00022687', 'A00023866', 'A00021085', 'A00022619', 'A00036897', 'A00019888', 'A00021058', 'A00022835', 'A00037495', 'A00026945', 'A00018716', 'A00026907', 'A00023330', 'A00016199', 'A00037238', 'A00023131', 'A00014120', 'A00021072', 'A00037665', 'A00022400', 'A00003150', 'A00024372', 'A00021081', 'A00022592', 'A00022653', 'A00013816', 'A00014839', 'A00031478', 'A00014225', 'A00013363', 'A00037007', 'A00020968', 'A00024301', 'A00024820', 'A00035469', 'A00029226', 'A00022915', 'A00022773', 'A00024663', 'A00036844', 'A00009207', 'A00024535', 'A00022727', 'A00011265', 'A00024546'